services:
  - type: web
    name: ygo-spreadsheet
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PORT
        value: 10000
